### ISSUE TITLE
Elite frame not working on PFui Turtle WoW

### ISSUE THREAD

**Issue by DGreatfox** [shagu/pfUI-eliteoverlay#6]
Currently running PF ui in Turtle wow and it does not seem to have any issues enabling the addon but for some reason I cannot see the dragon around the frames. No errors are present that I can see.

**Comment by shagu** [comment]
Works for me on Turtle WoW:
![Screenshot from 2022-09-09 09-59-59](https://user-images.githubusercontent.com/11586807/189301829-6db55b01-7c71-43e7-abc2-a328ef533654.png)

**Comment by DGreatfox** [comment]
Interesting, is there a setting in the options that needs to be turned on for it to be enabled?I have it just in the add-ons folder.

**Comment by shagu** [comment]
Not really, if it shows up in the addon list, you should see it around every elite and rare unit.
If it doesn't show up in the addon list, you maybe forgot to rename it (remove -master)

**Comment by DGreatfox** [comment]
I did remove the master portion from the tail of its folder but still to no avail. Looked at friendly elites and hostile elites and it still did not show.

**Comment by DGreatfox** [comment]
Ok I have every single addon turned off except for PFui and the elite frame and it does not want to show up still. Here is a picture of the addons in my folder and in game with only PFUI and eliteframe on. Still doesn't want to show. Is there a setting inside of PFUI that might disable it from showing?
![explorer_kzWsVukJNi](https://user-images.githubusercontent.com/16691035/189539670-357386b0-dc56-4677-84a9-94ff86967fbd.png)
![WoW_pqn6ONBF01](https://user-images.githubusercontent.com/16691035/189539678-f2106e58-a755-4d89-af37-ef326596b07b.png)

**Comment by Sneaky42** [comment]
Same issue, removed -master, dropped it in the addons folder, no dragon on the elite targets

**Comment by Sneaky42** [comment]
Found my issue, I was given the pfui-tbc version when i started on twow, I swapped it out with pfui vanilla from the site and it is working now, thank you
